name: Bump Version on Release PR Merge

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  bump-version:
    if: startsWith(github.head_ref, 'release')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # necesario para que `git` tenga todo el historial

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        run: |
          npm version patch -m "deploy: 🚀 version %s [ci skip]"
          git push origin HEAD:refs/heads/${{ github.head_ref }} --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
